### Get map boundary
GET http://localhost:8000/boundaries/current

### Get snow map overlay
GET http://localhost:8000/layers?overlay_attribute=snow&transport_mode=walk

### Get route by origin and destination address
POST http://localhost:8000/routes/by-address
Content-Type: application/json

{
  "transport_mode": "bike",
  "origin": "Nørrebro",
  "destination": "Bispebjerg",
  "options": {
    "method": "weighted",
    "weights": {
      "scenic": 40,
      "avoid_snow": 80,
      "avoid_uphill": 20
    }
  }
}

### Get route by origin and destination coordinates
POST http://localhost:8000/routes/by-coordinates
Content-Type: application/json

{
  "transport_mode": "walk",
  "origin": {
    "type": "Point",
    "coordinates": [
      12.538235,
      55.700772
    ]
  },
  "destination": {
    "type": "Point",
    "coordinates": [
      12.513641,
      55.663993
    ]
  }
}

### Reverse geocode coordinates to approximate address
GET http://localhost:8000/geocoding/reverse?longitude=12.538235&latitude=55.700772
