name: CI
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  backend:
    name: Back-End CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set Up uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: backend
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --frozen --all-extras
      - name: Run Ruff Format
        run: uv run ruff format --check --diff
      - name: Run Ruff
        run: uv run ruff check
      - name: Run basedpyright
        run: uv run basedpyright
      - name: Run pytest
        run: uv run pytest --cov app --cov-report term-missing
  frontend:
    name: Front-End CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set Up uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: backend
          enable-cache: true
      - name: Install Python Dependencies
        run: uv sync --directory ../backend --frozen --all-extras
      - name: Set Up pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: false
      - name: Set Up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install Node.js Dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Client
        run: make -C .. openapi
      - name: Run Prettier
        run: pnpm format:check
      - name: Run ESLint
        run: pnpm lint
      - name: Run tsc
        run: pnpm tsc:check
